In [1]:
# Import libraries
import numpy as np                                      # Calculating tools
import pandas as pd                                     # Data manipulation
import scipy.stats as stats                             # Statistics tools
import matplotlib.pyplot as plt                         # Data visualization
import seaborn as sns                                   # Modern data visualization
import plotly.graph_objects as go                       # Interactive visualization

from sklearn.preprocessing import OrdinalEncoder, StandardScaler, LabelEncoder   # Encode categorical variable,  Data normalization
from sklearn.model_selection import train_test_split                             # Create train, test set         
from sklearn import datasets                                                     # Some sample data sets 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA      # LDA model
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA   # QDA model
from sklearn.neighbors import KNeighborsClassifier                               # kNN model 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_score

import statsmodels.api as sm                     # Statistical models
import statsmodels.formula.api as smf            # Statistical models with formula supports
import ISLP

In [ ]:
train = pd.read_csv('data/train.csv', index_col=0)
train_labels = pd.read_csv('data/train_labels.csv', index_col=0)
test = pd.read_csv('data/test.csv', index_col=0)

In [4]:
train.head()

        Var1  Var2  Var3  ...          Var14998  Var14999  Var15000
ID                        ...
502504     0     0     0  ...               NaN       NaN       NaN
197332     0     0     0  ...               NaN       NaN       NaN
277830     0     0     0  ...           GD6M5hO       NaN       NaN
247676     0     0     0  ...  rbDCepHN5tF_ZSV6       NaN       NaN
972007     0     0     0  ...           GD6M5hO       NaN       NaN

[5 rows x 15000 columns]

In [5]:
train_labels.head(3)

        Target_appetency
ID
502504                 0
197332                 0
277830                 0

In [6]:
test.head()

        Var1  Var2  Var3  Var4  ...  Var14997  Var14998  Var14999  Var15000
ID                              ...
877149     0     0     0     0  ...       NaN   GD6M5hO       NaN       NaN
109603     0     0     0     0  ...       NaN       NaN       NaN       NaN
560424     0     0     0     0  ...       NaN       NaN       NaN       NaN
386592     0     0     0     0  ...       NaN       NaN       NaN       NaN
857379     0     0     0     0  ...       NaN       NaN       NaN       NaN

[5 rows x 15000 columns]

# Data Cleaning

In [11]:
# Only keeping the first 10 columns
train = train.iloc[:, :10]
test = test.iloc[:, :10]

In [12]:
X_train = train.fillna(0).values
X_test = test.fillna(0).values

In [13]:
y = train_labels['Target_appetency']
y.head()

ID
502504    0
197332    0
277830    0
247676    0
972007    0
Name: Target_appetency, dtype: int64

In [14]:
# Train KNN
knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
knn.fit(X_train, y)
preds = knn.predict_proba(X_test)[:, 1]

In [15]:
scores = cross_val_score(knn, X_train, y, cv=5, scoring='roc_auc')
print(f"AUC: {scores.mean():.4f}")

AUC: 0.4998

In [ ]:
# Submission
submission = pd.DataFrame({'Target_appetency': preds}, index=test.index)
submission.index.name = 'ID'
submission.to_csv('submission.csv')